name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: anybody/ammr-spine
          ref: master-ammr-3.0
          path: ammr-spine
          token: ${{ secrets.AMMR_SPINE_READ_TOKEN }}

      # - uses: anybody/setup-anybody@main
      #   with:
      #     anybody-version: "7.5.0"
      #     anybody-version-suffix: "Beta"
      #     python-environment: "minimal"



        