name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create AnyBody Folders
        run: |
          mkdir $HOME/AnyBody
          mkdir $HOME/Python




      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          cache-environment: true
          environment-name: Python


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd $HOME/micromamba/envs/Python
          ls

          echo Add other actions to build,
          echo test, and deploy your project.
