name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create AnyBody Folders
        run: |
          mkdir $HOME/AnyBody
          Add-MpPreference -ExclusionPath $HOME/AnyBody
          Add-MpPreference -ExclusionPath $HOME/micromamba-root/envs

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: full-ams-python.conda-lock.yml
          cache-environment: true
          environment-name: Python
      
      - name: Download and extract AnyBody
        run: |
          $url = "https://anybodycloudci.blob.core.windows.net/windows-anybodycon/anybody-minimal-7.5.0-beta6.zip"
          $output = "$HOME/AnyBody"
          Add-Type -Assembly System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::ExtractToDirectory($url, $output)         

      - name: Set Python environment for AnyBody
        run: echo "ANYBODY_PATH_PYTHONHOME=$HOME/micromamba-root/envs" >> $GITHUB_ENV
    
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $env:ANYBODY_PATH_PYTHONHOME

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd $HOME/AnyBody
          ls

          echo Add other actions to build,
          echo test, and deploy your project.
