name: Test AMMR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true


jobs:
  linux-tests: 
    strategy:
      fail-fast: false
      matrix:
        test_group: [1, 2, 3, 4, 5, 6, 7, 8]
    
    runs-on: ubuntu-latest
    container: ghcr.io/anybody/anybodycon-github-actions:latest_Beta

    steps:
      - uses: actions/checkout@v4
        with:
          repository: anybody/ammr
          ref: clean-up-pytest-plugins
          path: ammr
          token: ${{ secrets.AMMR_SPINE_READ_TOKEN }}

      - name: Install pytest-split
        run: micromamba install -y --name base -c conda-forge pytest-split=0.8.1
  
      - name: Run tests
        run: |
          cd ammr/Tests
          pytest --splits 8 --group ${{ matrix.test_group }}  --durations=10 --runslow
        env:
          RLM_LICENSE: ${{ secrets.RLM_LICENSE }}
          RLM_LICENSE_PASSWORD: ${{ secrets.RLM_LICENSE_PASSWORD }}

  windows-tests:
    strategy:
      fail-fast: false
      matrix:
        test_group: [1, 2, 3, 4, 5, 6, 7, 8]

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: anybody/ammr
          ref: clean-up-pytest-plugins
          path: ammr
          token: ${{ secrets.AMMR_SPINE_READ_TOKEN }}

      - uses: anybody/setup-anybody@main
        name: Install AnyBody
        with:
          anybody-version: "7.5.0"
          anybody-version-suffix: "Beta"
          python-environment: "minimal"

      - name: Install pytest
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ammr/Tests/test-environment.yml
          init-shell: powershell
          cache-environment: true

      - name:
        run: |
          cd ammr/Tests
          pytest --splits 8 --group ${{ matrix.test_group }} --durations=10 --runslow
        
        env:
          RLM_LICENSE: ${{ secrets.RLM_LICENSE }}
          RLM_LICENSE_PASSWORD: ${{ secrets.RLM_LICENSE_PASSWORD }}
